param([string]$UnicodeVersion = '17.0.0')
$ErrorActionPreference = 'Stop'
$taskRanges = [Collections.Generic.List[object]]::new()
foreach ($taskSource in @('EastAsianWidth.txt', 'emoji/emoji-data.txt')) {
    $taskData = (Invoke-WebRequest "https://www.unicode.org/Public/$UnicodeVersion/ucd/$taskSource").Content
    foreach ($taskLine in ($taskData -split "`n")) {
        if ($taskLine -match '^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(W|F|Emoji_Presentation)\s*(?:#|$)') {
            $taskStart = [Convert]::ToInt32($Matches[1], 16)
            $taskEnd = if ($Matches[2]) { [Convert]::ToInt32($Matches[2], 16) } else { $taskStart }
            $taskRanges.Add(@{ Start = $taskStart; End = $taskEnd })
        }
    }
}
$taskMerged = [Collections.Generic.List[object]]::new()
foreach ($taskRange in ($taskRanges | Sort-Object Start, End)) {
    if ($taskMerged.Count -gt 0 -and $taskRange.Start -le $taskMerged[$taskMerged.Count - 1].End + 1) {
        $taskMerged[$taskMerged.Count - 1].End = [Math]::Max($taskRange.End, $taskMerged[$taskMerged.Count - 1].End)
    } else { $taskMerged.Add($taskRange) }
}
$taskRows = $taskMerged | ForEach-Object { '        (0x{0:X}, 0x{1:X}),' -f $_.Start, $_.End }
$taskOutput = @"
// Generated by scripts/update-unicode-widths.ps1 from Unicode $UnicodeVersion.
// EastAsianWidth W/F and Emoji_Presentation. See docs/UNICODE.md and licenses/Unicode.txt.
namespace Charloom.Core;

internal static class UnicodeWidthData
{
    internal static readonly (int Start, int End)[] Wide =
    [
$($taskRows -join "`n")
    ];
}
"@
$taskRoot = Split-Path $PSScriptRoot -Parent
[IO.File]::WriteAllText((Join-Path $taskRoot 'src/Charloom.Core/UnicodeWidthData.cs'), $taskOutput + "`n", [Text.UTF8Encoding]::new($false))
New-Item -ItemType Directory -Force (Join-Path $taskRoot 'licenses') | Out-Null
Invoke-WebRequest 'https://www.unicode.org/license.txt' -OutFile (Join-Path $taskRoot 'licenses/Unicode.txt')
Write-Output "Generated $($taskMerged.Count) Unicode width ranges."
